<OverviewWidget>:
    StackLayout:
        #Label:
        #    text: "Test 123"
        #    size_hint: None, None
        #    text_size: self.size
        #    valign: "top"
        list: list
        ListView:
            id: list

<OverviewEntry>:
    StackLayout:
        orientation: "lr-tb"
        Label:
            id: songName
            size_hint: .5, None
        Label:
            id: artistName
            size_hint: .5, None